name: PR Title Linter

description: Lints the PR title to ensure it contains a ticket ID or [NO-TICKET]

inputs:
  pr-title:
    description: The title of the PR
    required: true

  ticket-prefix:
    description: Comma-separated list of valid ticket prefixes (e.g. `FOO,BAR,BAZ`).
    required: true

runs:
  using: composite
  steps:
    - name: Lint PR title
      shell: bash
      env:
        PR_TITLE: ${{ inputs.pr-title }}
        TICKET_PREFIX: ${{ inputs.ticket-prefix }}
      run: |
        echo "PR title: $PR_TITLE"
        echo "Allowed prefixes: $TICKET_PREFIX"

        # Functions for colored output
        print_red() { 
          echo -e "\033[31m$1\033[0m" 
        }

        print_green() { 
          echo -e "\033[32m$1\033[0m" 
        }

        # Loop through each prefix in the comma-separated list
        for CURRENT_PREFIX in ${TICKET_PREFIX//,/ }; do
          # Use the raw prefix directly (no printf '%q')
          ESCAPED_TICKET_PREFIX="$CURRENT_PREFIX"

          # Define regex patterns
          TICKET_REGEX="^\[((${ESCAPED_TICKET_PREFIX}-[0-9]+)(,[[:space:]]*${ESCAPED_TICKET_PREFIX}-[0-9]+)*)\]"
          NO_TICKET_REGEX="^\[NO-TICKET\]"

          echo ""
          echo "Running check for prefix: $ESCAPED_TICKET_PREFIX"
          if [[ $PR_TITLE =~ $TICKET_REGEX ]] || [[ $PR_TITLE =~ $NO_TICKET_REGEX ]]; then
            print_green "✅ PR title is valid."
            exit 0
          fi
        done

        # If we get here, no prefix matched
        print_red "❌ PR title is invalid."
        echo ""
        print_red "### Expected PR Title Format:"
        print_red "- The PR title must start with either [<PREFIX>-<number>],"
        print_red "  multiple ticket IDs like [<PREFIX>-<number>, <PREFIX>-<number>],"
        print_red "  or [NO-TICKET]."
        echo ""
        print_red "### Examples (assuming prefix LAU):"
        print_red "- [LAU-123] Add new authentication method"
        print_red "- [LAU-123, LAU-456] Implement new features"
        print_red "- [NO-TICKET] Fix typo in documentation"
        echo ""
        print_red "Please update your PR title to match the required format."

        # Add error message to GitHub Actions logs
        echo "::error title=Invalid PR Title::The provided PR title is invalid, check the logs for more information on the possible values."
        exit 1
